import { useState, useCallback, useEffect } from "react";

/**
 * Prediction Mode Hook - Algorithm-Agnostic
 * 
 * Uses prediction_points from trace metadata (generated by backend).
 * Works for any algorithm that implements get_prediction_points().
 */
export const usePredictionMode = (trace, currentStep, nextStep) => {
  const [predictionMode, setPredictionMode] = useState(true);
  const [showPrediction, setShowPrediction] = useState(false);
  const [activePrediction, setActivePrediction] = useState(null);
  const [predictionStats, setPredictionStats] = useState({
    total: 0,
    correct: 0,
  });

  // Get prediction points from trace metadata
  const predictionPoints = trace?.metadata?.prediction_points || [];

  // Auto-detect prediction points based on metadata
  useEffect(() => {
    if (!trace || !predictionMode) {
      setShowPrediction(false);
      setActivePrediction(null);
      return;
    }

    // Find prediction point matching current step
    const matchingPrediction = predictionPoints.find(
      (p) => p.step_index === currentStep
    );

    if (matchingPrediction) {
      setActivePrediction(matchingPrediction);
      setShowPrediction(true);
    } else {
      setActivePrediction(null);
      setShowPrediction(false);
    }
  }, [currentStep, trace, predictionMode, predictionPoints]);

  const handlePredictionAnswer = useCallback((userAnswer) => {
    if (!activePrediction) return;

    const isCorrect = userAnswer === activePrediction.correct_answer;

    setPredictionStats((prev) => ({
      total: prev.total + 1,
      correct: prev.correct + (isCorrect ? 1 : 0),
    }));

    setShowPrediction(false);
    setActivePrediction(null);
    nextStep(); // Advance step after answering
  }, [activePrediction, nextStep]);

  const handlePredictionSkip = useCallback(() => {
    setShowPrediction(false);
    setActivePrediction(null);
    nextStep(); // Advance step after skipping
  }, [nextStep]);

  const togglePredictionMode = useCallback(() => {
    setPredictionMode((prev) => !prev);
    setShowPrediction(false);
    setActivePrediction(null);
  }, []);

  const resetPredictionStats = useCallback(() => {
    setPredictionStats({ total: 0, correct: 0 });
  }, []);

  return {
    predictionMode,
    showPrediction,
    activePrediction, // New: Expose the full prediction object
    predictionStats,
    togglePredictionMode,
    handlePredictionAnswer,
    handlePredictionSkip,
    resetPredictionStats,
  };
};