// frontend/src/utils/predictionUtils.js
/**
 * Algorithm-Agnostic Prediction Utilities
 * 
 * Prediction mode now uses metadata-driven approach.
 * All prediction data comes from trace.metadata.prediction_points
 * generated by backend's get_prediction_points() method.
 */

/**
 * Get encouraging feedback based on accuracy percentage
 * @param {number} accuracy - Percentage correct (0-100)
 * @returns {Object} - Object with message and color
 */
export const getAccuracyFeedback = (accuracy) => {
  if (accuracy >= 90) {
    return {
      message: "🎉 Excellent! You've mastered this algorithm!",
      color: "emerald",
      emoji: "🎉"
    };
  } else if (accuracy >= 70) {
    return {
      message: "👍 Great job! You understand the core logic.",
      color: "emerald",
      emoji: "👍"
    };
  } else if (accuracy >= 50) {
    return {
      message: "📚 Good start! Keep practicing to improve.",
      color: "amber",
      emoji: "📚"
    };
  } else {
    return {
      message: "💡 Keep practicing! Try the step-by-step mode to understand each decision.",
      color: "red",
      emoji: "💡"
    };
  }
};

/**
 * Format prediction statistics for display
 * @param {Object} stats - {total: number, correct: number}
 * @returns {Object} - Formatted stats with accuracy and feedback
 */
export const formatPredictionStats = (stats) => {
  const accuracy = stats.total > 0 
    ? Math.round((stats.correct / stats.total) * 100)
    : 0;
  
  const feedback = getAccuracyFeedback(accuracy);
  
  return {
    ...stats,
    accuracy,
    ...feedback
  };
};